create table if not exists public.referral_clicks (
  id bigint generated by default as identity primary key,
  platform_id text not null,
  platform_slug text,
  platform_name text,
  referral_label text,
  referral_url text,
  clicked_at timestamptz not null default now()
);

create index if not exists referral_clicks_clicked_at_idx
  on public.referral_clicks (clicked_at desc);

create index if not exists referral_clicks_platform_id_idx
  on public.referral_clicks (platform_id);

alter table public.referral_clicks enable row level security;

grant insert on public.referral_clicks to anon, authenticated;
grant select on public.referral_clicks to authenticated;
grant usage, select on sequence public.referral_clicks_id_seq to anon, authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'referral_clicks'
      and policyname = 'Allow public referral click inserts'
  ) then
    create policy "Allow public referral click inserts"
      on public.referral_clicks
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'referral_clicks'
      and policyname = 'Allow admins to read referral clicks'
  ) then
    create policy "Allow admins to read referral clicks"
      on public.referral_clicks
      for select
      to authenticated
      using (
        exists (
          select 1
          from public.admins
          where admins.user_id = auth.uid()
            and admins.role = 'admin'
        )
      );
  end if;
end
$$;
